### ISSUE TITLE
Include bonus column in Rounds table

### ISSUE THREAD

**Issue by sivagollapalli** [joshsoftware/code-curiosity#66] opened 2016-08-02 05:36 UTC
On a first glance, I am seeing 72 points on left side whereas on the right side if I add total points then it is not equal to 72. After checking points history, I find out that I got GoalBonus. Would it be better if we include bonus column in rounds table to avoid this confusion?

![rounds](https://cloud.githubusercontent.com/assets/280199/17318075/ff880546-58a0-11e6-8332-3239bb031b27.png)
![points](https://cloud.githubusercontent.com/assets/280199/17318076/0076ce4c-58a1-11e6-936b-79f6acf1b3e7.png)

**Comment by gautamrege** [comment] 2016-08-02 06:52
Thanks for the ticket but this is correct and it was intended like this.

The Round points are earned,  bonus points are given as an incentive. Hence the Points History give you a transaction history.  

Closing for now.

**Closed by gautamrege** 2016-08-02 06:52 UTC
