### ISSUE TITLE
PR Review comments and comments activity on commits aren't evalulated

### ISSUE THREAD

**Issue by nixmaniack** [joshsoftware/code-curiosity#122] opened 2016-09-15 18:40 UTC
I'm not sure if you can evaluate and score comments on PR review code or comments on commits but if you go by the same logic of evaluating comments on issues - it should be doable. 

Right now, they're not even visible in activities but I think, review comments should be given more weightage as it might provide more constructive review/contribution.

**Comment by gautamrege** [comment] 2016-09-16 03:05
Yes - we agree. this is WIP. Closing as duplicate of  #91 
If you have more thoughts / ideas or feedback, please update it on that ticket.

**Closed by gautamrege** 2016-09-16 03:05 UTC
